version: "3.8"

services: 
  postgre-example1: 
    container_name: postgre-example1
    image: postgres:13.4 
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: wildan1207
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
      - type: volume
        source: postgre-data1
        target: /var/lib/postgresql/data
        read_only: false
  postgre-example2: 
    container_name: postgre-example2
    image: postgres:13.4 
    ports:
      - "5434:5434"
    environment:
      POSTGRES_PASSWORD: wildan1207
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
      - type: volume
        source: postgre-data2
        target: /var/lib/postgresql/data
        read_only: false

volumes: 
  postgre-data1: 
    name: postgre-data1
  postgre-data2: 
    name: postgre-data2